services:
  web:
    image: angrysine/frontend_todo_list

    ports:
      - "3000:3000"

    depends_on:
      - api
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  api:
    image: angrysine/backend_todo_list
    ports:
      - "5000:5000"
    restart: always

    depends_on:
      - db
